theme: jekyll-theme-architect

title: [JavaMail]
description: [JavaMail Reference Implementation]

links:
  source: https://github.com/javaee/javamail
  javadocs: docs/api/
  download: https://github.com/javaee/javamail/releases
  mailinglist: https://javaee.groups.io/g/javamail
  faq: FAQ
